### ISSUE TITLE
webform spacing too tall

### ISSUE THREAD

**Issue by idahoboy** [idahofishgame/bison#1]
https://github.com/idahofishgame/bison/blob/master/css/bison.css line 128

`.webform-component label, #webform-component-optional, #edit-actions { margin-top: 40px; }`

margin is 40px?

What would it break to remove/reduce that?

**Comment by stupiddingo** [comment]
Resolved by https://github.com/idahofishgame/bison/commit/b903c5cf23c37ca101188fd43e41c4ee12ed11ab
